apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{claimName}}
  labels:
    app: WholeTale
    instanceId: "{{instanceId}}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{volumeSize}}